steps:

  # Build uberjar
  - name: clojure:openjdk-11-tools-deps
    args: ['bash', '../cloudbuild/build.sh']
    dir: 'server'
    secretEnv: ['AWS_CREDENTIALS_ACCESS', 'AWS_CREDENTIALS_SECRET', 'AWS_REGION', ]

#
#  # Copy uberjar to compute engine vm
#  - name: gcr.io/cloud-builders/gcloud
#    args: ['compute', 'scp', 'target/metabase.jar', 'metabase:/opt/metabase/metabase.jar', '--project=hti-${_ENV}', '--zone=europe-west1-b']
#    dir: 'server'
#
#  # Restart payment-switch service
#  - name: gcr.io/cloud-builders/gcloud
#    args: ['compute', 'ssh', 'metabase', '--command=/opt/metabase/restart.sh', '--project=hti-${_ENV}', '--zone=europe-west1-b']
#    dir: 'server'
#


substitutions:
  _ENV: 'apps'

availableSecrets:
  secretManager:
    - versionName: projects/1006690200145/secrets/aws-credentials-secret-access-key/versions/1
      env: 'AWS_CREDENTIALS_SECRET'
    - versionName: projects/1006690200145/secrets/aws-credentials-access-key/versions/1
      env: 'AWS_CREDENTIALS_ACCESS'
    - versionName: projects/1006690200145/secrets/aws-region/versions/1
      env: 'AWS_REGION'


